.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH LLGAL 1 "FEBRUARY 2005" "Version 0.4" "Version 0.4"


.SH NAME
llgal \- Loulous Image Gallery generator


.SH SYNOPSIS
.B llgal 
.I [-option1 -option2 ...]


.SH DESCRIPTION
.B llgal
is a quick and easy program for placing your images and movies online with
just one command-line. It generates a pretty good-looking set of static HTML
slides even with its default settings.  To try it out just run 
.B llgal 
in a directory with
.IR jpg ", " gif ", " png ", " mpg " or " avi
files and check the output in a web browser.  You can adjust the
appearance of the image gallery with the many options listed below or
(if you know a bit of HTML) by modifying the
.IR indextemplate.html ", " slidetemplate.html " and " llgal.css
files in the
.IR .llgal.files/ " subdirectory that appeared in your"
image directory.
.B llgal
also checks for the existence of a
.I "$HOME/.llgal"
directory where users can store their own templates, overriding
the site-wide 
.IR "/usr/share/llgal" .


.SH LAYOUT OPTIONS

.TP
.B -a
Write image dimensions and sizes under each thumbnail on the index page,
and under each slide if --bigy was passed.
This only works if the ImageMagick command
.BR identify " is present."

.TP
.B --ad
Like
.B -a
but write only the image dimensions.

.TP
.B --as
Like
.B -a
but write only the image sizes.

.TP
.B --asu " <s>"
Allow to define the unit used to show file sizes. Default is
.IR kB "."

.TP
.BI --bigy " <n>"
Like
.B -y
but operates on the image slides, not the thumbnails.  Scales image
slides to some medium height (e.g.
.IR 400 "),"
adjusting their width accordingly.  Useful if your digital camera
spits out large images, like 1600x1200.  The originals aren't affected,
but scaled copies of your images are stored with the 
.I ".slide"
prefix and thumbnails link to these copies.  Clicking on the scaled
copies in the HTML slides lets users see the full unscaled images.
You must use
.B -f
between two consecutive runs when you've changed the value of
.BR "--bigy" .

.TP
.BI -c
First generate and then publish image slide captions. The first invocation of
.B llgal -c
generates in
.I .llgal.files
a
.I captions
file that you may edit.  The format of this file is very simple.
See
.SM
.B CAPTIONS
for details.
A second invocation of
.B llgal -c
will read your
.I captions
file, include your captions in the slides and rearrange them if necessary.

.TP
.BI -C
Generates
.I captions
from file names (strips suffix).

.TP
.BI --ce
Generates
.I captions
from EXIF tags that may exist in JPEG files

.TP
.BI --con " options"
Command line options to pass on to
.BR convert
internally (see its man page).  This affects all thumbnails
and, if
.BI --bigy
is given, the medium-size slides too.  You can set the
.I -quality
or go crazy with
.IR -negate ", " -noise ", etc."
(the last two only work with
.BR convert " if " ImageMagick " is installed)."
.BI --con
may be used several times on the same command line.

.TP
.BI -d " <dir>"
Operate on image files in directory
.IR <dir> ,
which is also where the HTML and thumbnail files will be generated.
The default is the current directory.

.TP
.BI -i " <file>"
Name of the main thumbnail index file.  The default is
.IR index.html ,
as desirable for most web servers.

.TP
.BI -k
Use the image captions for the HTML slide titles.
The default behavior is to use the image names.

.TP
.BI -n
Use the image file names for the HTML slide files.  Otherwise
the default behavior is to simply name your slides
.IR 1.html ", " 2.html ", "
and so on.

.TP
.BI -p " <n>"
The cellpadding value of the thumbnail index tables.
The default is 3.

.TP
.BI -r
Omit the film reel effect altogether.  For a simpler look you
can also set the thumbnail background to be the same as the main
index page background with the tile background-color option in the
.IR llgal.css " file."

.TP
.BI -R
Enable recursive mode. Subdirectories will be added to the gallery.

.TP
.B -s
For the simplest setup, omit all HTML slides.  Clicking the thumbnails on 
the main page will just take users to the plain image files.

.TP
.BI --sp " <s>"
Change slide image filename prefix

.TP
.BI -t " <n>"
Height (in pixels) of the tiled image used to simulate the top
and bottom "film reel" effect on the thumbnail index page.  This
is 21 for the default
.I .tile.png
image used, but you should set it otherwise if you replace that
file with your own design.

.TP
.BI --title " <s>"
Substitutes the string 
.I <s>
for "<!--TITLE-->" in the index. The default is "Index of Pictures".

.TP
.BI --tp " <s>"
Change thumbnail image filename prefix.

.TP
.BI -u
Write image captions under each thumbnail on the index page.
If you have a
.I captions
file (see options -c or -C) then the captions are read from there,
else the file names are used (but the file extension is stripped).

.TP
.BI -w " <n>"
Set the thumbnail rows to be
.I <n>
images wide in the main index file.  Default is 5.

.TP
.BI --wx " <n>"
Set the thumbnail rows to be 
.I <n>
pixels wide at maximum. The number of thumbnails per row, given in
.BI -w
is reduced if necessary. Default is to honor
.BI -w
without regard to the resulting row width.

.TP
.BI -x
Omit the image count from the captions.

.TP
.BI --xy " <n>"
Scale thumbnails to
.I <n>
pixels along their longest dimension.  This value is passed to
.B pnmscale
and only works properly for
.I jpg
images.

.TP
.BI -y " <n>"
Scale all thumbnails to the same height of 
.IR <n> " pixels."
The default is 75 pixels.


.SH BEHAVIOR OPTIONS

.TP
.BI --clean
Remove all files
.B llgal
may have created earlier and that user did not modify since.

.TP
.BI --cleanall
Remove all files
.B llgal
may have created earlier. This includes thumbnails, scaled down slides, all 
HTML files, caption file, reel-effect picture, indextemplate and slidetemplate 
and the stylesheet file.

.TP
.BI --config " <file>"
Read the file
.I file
as a configuration.
See
.SM
.B CONFIGURATION
.BI --config
may be used several times on the same command line.

.TP
.BI -f
Force thumbnail regeneration.  Also forces medium-slide regeneration if
.BI --bigy
is given.  Otherwise
.B llgal
will not regenerate these files if they already exist, and you may
end up with stale copies.  Definitely use
.BI -f
between two runs where you've changed the value of 
.BR --bigy " or " --con "."

.TP
.BI "-h, --help"
Display brief help.

.TP
.BI --option " 'variable = value'"
Modify llgal configuration.
See
.SM
.B CONFIGURATION
.BI --option
may be used several times on the same command line.

.TP
.BI --www
Make all
.B llgal
files world-readable.


.SH CAPTIONS
When called with
.I -c
.B llgal
check whether a
.IR captions
file exists in the
.IR .llgal.files
subdirectory.
If not, it does nothing but generating it from images and movies
that exists in the local directory.
If it exists, it uses it to generate
.IR captions
in the gallery.
The order of the captions in this file determines the order in the gallery.

.B IMG: <filename> ---- <caption>
.RS
defines an image (
.B IMG:
is the default type).
.RE
.B MVI: <filename> ---- <linkname> ---- <caption>
.RS
defines a movie.
.RE
.B TXT: <text in slide> ---- <caption>
.RS
defines a text slide.
.RE
.B LNK: <url> ---- <linkname> ---- <caption>
.RS
defines a link slide.
.RE
.B DIR: <dir> ---- <linkname> ---- <caption>
.RS
defines a subdirectory slide.
.RE
.B TITLE: <title>
.RS
defines the title of the gallery.
.RE
.B INDEXHEAD: <one header>
.RS
defines a header (multiple ones are possible).
.RE
.B INDEXFOOT: <one footer>
.RS
defines a footer (multiple ones are possible).
.RE
.TP
Note that you can use whatever HTML syntax in the captions.
.RE
Line begining with a
.RI #
are ignored.


.SH CONFIGURATION

Before parsing command line options, llgal reads several configuration
files. It starts with
.IR /etc/llgalrc
then reads
.IR $HOME/.llgalrc
then the 
.IR .llgalrc
file in the gallery directory
and finally the local
.IR .llgalrc
file.
Additional configuration files may also be defined with the
.I --config
option.

These files may change llgal configuration in the same way command
line options do, and even more.
All following options may also be used on the command line through
.I "--option 'variable = value'"\fR.

See also
.IR /etc/llgalrc
for details about these options and their default values.

.B llgal directories:

.I llgal_share_dir = "path"
.RS
The location of llgal share directory where template are stored.
.RE
.I user_share_dir = "path"
.RS
The location of the per-user share directory wher template are stored.
If they exists, these files are used instead of the system-wide files.
.RE

.B Names of generic llgal files:

.I css_filename = "filename.css"
.RS
Name of the CSS file.
.RE
.I filmtile_filename = "filename.png"
.RS
Name of the film tile image.
.RE
.I indextemplate_filename = "filename"
.RS
Name of the HTML index template that will be taken from common directories.
.RE
.I slidetemplate_filename = "filename"
.RS
Name of the HTML slide template that will be taken from common directories.
.RE

.B Location and name of generated files:

.I destination_dir = "path"
.RS
Directory of the gallery [-d <s>].
.RE
.I local_llgal_dir = "subdirectory"
.RS
The name of the subdirectory where llgal generated files will be stored.
.RE
.I scaled_image_filenameprefix = "filenameprefix"
.RS
Prefix used to determine slide-image filenames from
original images (in case of --bigy) [--sp <s>].
.RE
.I thumbnail_image_filenameprefix = "filenameprefix"
.RS
Prefix used to determine thumbnail filenames from
original images [--tp <s>].
.RE

.B Index:

.I index_filename = "index.html"
.RS
Name of the generated index file [-i <s>].
.RE
.I index_title = "string"
.RS
Title of the gallery [--title <s>].
.RE
.I index_cellpadding = <n>
.RS
Cellpadding in the index table [-p <n>].
.RE
.I pixels_per_row = <n>
.RS
Pixels per row of thumbnails in index [-wx <n>].
.RE

.B Film effect:

.I show_no_film_effect = <0/1>
.RS
Omit film reel effect [-r].
.RE
.I tile_height = <n>
.RS
Film tile height [-t <n>].
.RE

.B Thumbnails:

.I thumbnail_height_max = <n>
.RS
Maximal height of thumbnails [-y <n>].
.RE
.I thumbnail_width_max = <n>
.RS
Maximal width of thumbnails [-xy <n>]
.RE
.I thumbnails_per_row = <n>
.RS
Thumbnails per row in index [-w <n>].
.RE

.B Slides:

.I make_no_slides = <0/1>
.RS
Make no slides [-s].
.RE
.I make_slide_filename_from_filename = <0/1>
.RS
Use filenames as slide filenames [-n].
.RE
.I make_slide_filename_from_extension = <0/1>
.RS
Also use extension in slide filename when generated from filename.
.RE
.I make_slide_title_from_caption = <0/1>
.RS
Generate slide titles from captions [-k].
.RE
.I show_no_slide_counter = <0/1>
.RS
Do not show slide counter in captions [-x].
.RE
.I slide_filenameprefix = <s>
.RS
Prefix of generated HTML slide filenames.
.RE
.I slide_filenameprefix_nofile = <s>
.RS
Prefix of slide filenames when generated from filename
while there's no file associated (text, link, ...).
.RE
.I slide_height_max = <n>
.RS
Maximal height of slides [--bigy <n>].
.RE
.I text_slide_width = <n>
.RS
Default width of text slides.
.RE
.I text_slide_height = <n>
.RS
Default height of text slides.
.RE

.B Captions:

.I captions_filename = "filename"
.RS
Name of the caption file that will be generated the first time llgal
is called with -c.
.RE
.I caption_removal_line = "string"
.RS
This line will be added to the caption file llgal will generate the
first time it is called with -c. If the user doesn't want igal to
remove this caption file when called with -clean, it just needs to
remove this line from the file.
.RE
.I make_caption_from_filename = <0/1>
.RS
Generate captions from filenames [-C].
.RE
.I make_caption_from_exif = <0/1>
.RS
Generate captions from EXIF tags in JPEG images [--ce].
.RE
.I show_caption_under_thumbnails = <0/1>
.RS
Write captions under thumbnails [-u].
.RE
.I show_dimensions = <0/1>
.RS
Show image dimensions [-a, -ad].
.RE
.I show_size = <0/1>
.RS
Show file sizes [-a, -as].
.RE
.I show_size_unit = "string"
.RS
Unit to be used when printing sizes [-asu <s>]
.RE
.I use_caption_file = <0/1>
.RS
Use a caption file [-c].
.RE

.B Various:

.I convert_options = "string"
.RS
Options to pass to convert [--con <s>].
This option may be used several times.
.RE
.I scaled_convert_options = "string"
.RS
Additional options to pass to convert when creating slides.
.RE
.I thumbnail_convert_options = "string"
.RS
Additional options to pass to convert when creating thumbnails.
.RE
.I config_file = <s>
.RS
Additional configuration file [--config <s>].
This option may be used several times.
.RE
.I make_recursive = <0/1>
.RS
Look at subdirectories [-R].
.RE
.I www_access_rights = <0/1>
.RS
Make all generated files world readable [-www].
.RE


.SH NOTES
Note that all numerical options may be resetted to their default value
by setting them a negative value.


.SH FILES
.RE
.I /etc/llgalrc
.I $HOME/.llgalrc
.I .llgalrc
.RS
System-wide, per-user and local configuration files. See
.SM
.B CONFIGURATION
for details.

.RE
.I /usr/share/llgal/indextemplate.html
.RS
The default index template file.
.RE
.I /usr/share/llgal/slidetemplate.html
.RS
The default file used to generate slides.
.RE
.I /usr/share/llgal/llgal.css
.RS
The default style sheet template.
.RE
.I /usr/share/llgal/tile.png
.RS
The tiled image used for the "film reel" effect.
.RE
All four files are copied to your image directory as dotfiles the
first time you run
.BR llgal .
Modify the local copies (but keep their names) if you need to further 
alter the appearance of your slide show (also see
.BR "-t" ")."
.B llgal
also checks for the existence of a
.I "$HOME/.llgal"
directory where users can store their own templates, overriding
the site-wide 
.IR "/usr/share/llgal" .


.SH EXAMPLES
Run
.B llgal
in a directory with 
.IR jpg ", " gif ", " png ", " mpg " or " avi
files to see what it does.  Then
play with the options described above and use
.B -h
if you need a quick listing.


.SH BUGS
There are always some.  If you find any let me know.


.SH AUTHOR
Brice Goglin <Brice.Goglin@ens-lyon.org>
