.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH LLGAL 1 "FEBRUARY 2005"

.SH NAME
llgal \- Loulous Image Gallery generator


.SH SYNOPSIS
.B llgal 
.I [-option1 -option2 ...]


.SH DESCRIPTION
.B llgal
is a quick and easy program for placing your images and movies online with
just one command-line. It generates a pretty good-looking set of static HTML
slides even with its default settings.  To try it out just run 
.B llgal 
in a directory with
.IR jpg ", " tif ", " gif ", " png ", " mpg ", " mov " or " avi
files and check the output in a web browser.  You can adjust the
appearance of the image gallery with the many options listed below or
(if you know a bit of HTML) by modifying the
.IR llgal.css
files in the
.IR .llgal/ " subdirectory that appeared in your"
image directory, or by defining
.IR indextemplate.html " or " slidetemplate.html
files.
.B llgal
also checks for the existence of a
.I "$HOME/.llgal"
directory where users can store their own templates, overriding
the site-wide 
.IR "/usr/share/llgal" .
See
.SM
.B FILES
for details.


.SH BEHAVIOR OPTIONS

.TP
.BI --clean
Remove all files
.B llgal
may have created earlier and that user did not modify since.

.TP
.BI --cleanall
Remove all files
.B llgal
may have created earlier. This includes thumbnails, scaled down slides, all 
HTML files, captions file, film effect picture, indextemplate and slidetemplate 
and the stylesheet file.

.TP
.BI --config " <file>"
Read the file
.I file
as a configuration.
See
.SM
.B CONFIGURATION
.BI --config
may be used several times on the same command line.

.TP
.BI -d " <dir>"
Operate on image files in directory
.IR <dir> ,
which is also where the HTML and thumbnail files will be generated.
The default is the current directory.

.TP
.BI -f
Force thumbnail regeneration.  Also forces medium-slide regeneration if
.BI --bigxy or --bigy
is given.  Otherwise
.B llgal
will not regenerate these files if they already exist, and you may
end up with stale copies.  Definitely use
.BI -f
between two runs where you've changed the value of 
.BR --bigxy, --bigy " or " --con "."

.TP
.BI --gc
Generate slide captions in
.IR ".llgal/captions"
file that you may edit.  The format of this file is very simple.
See
.SM
.B CAPTIONS
for details.
These captions may then be modified by the user.
The file will be automatically used next time
.B llgal
is invoked.
.BI --gc
might also be used to update the
.I captions
file when new files were added to the working directory.

.TP
.BI --gencfg " <file>"
Output configuration in
.IR file
for a futur reutilization through
.BI --config
See
.SM
.B CONFIGURATION
.BI --config

.TP
.BI --gt " [<dir>]"
Copy template files to the directory.
The special value
.IR local
might be used for the local
.I .llgal
directory, while
.IR user
might be used for the user
template directory
.I $HOME/.llgal \fR.
Any other directory is acceptable.
.I llgal
will create the target directory if it does not exist.
The argument is optional.
Its default value is
.IR local \fR.
See
.SM
.B FILES
for details about template files.

.TP
.BI "-h, --help"
Display brief help.

.TP
.BI --option " 'variable = value'"
Modify llgal configuration.
See
.SM
.B CONFIGURATION
.BI --option
may be used several times on the same command line.

.TP
.BI -R
Enable recursive mode.
.B llgal
will be run inside subdirectories.
The list of subdirectories has to be either detected by
.B -S
(which is not implied by
.B -R
) or defined in the captions file with
.B DIR:
entries.
This option might be used either to generate galleries
in all subdirectories, or their captions files.

Note that recursive cleaning (
.BI -R
used together with
.BI --clean
or
.BI --cleanall
) will
.B not
check that a subdirectory is in the captions file.
All not-dot-begining subdirectories will be cleaned.

.TP
.BI --templates " <dir>"
Add a directory to the list of template locations.

.TP
.BI "-v, --version"
Display llgal version.


.SH LAYOUT OPTIONS

.TP
.B -A
All files in the current directory will get a slides,
except .html or dot-begining files.
Files are matched as images or movies first, and then
reverted as simple files instead.
See
.B -S
for details about adding slides for subdirectories.

.TP
.B -a
Write image dimensions and sizes under each thumbnail on the index page,
and under each slide if --bigy or --bigxy was passed.
This only works if the ImageMagick command
.BR identify " is present."

.TP
.B --ad
Like
.B -a
but write only the image dimensions.

.TP
.B --as
Like
.B -a
but write only the image sizes.

.TP
.B --asu " <s>"
Allow to define the unit used to show file sizes. Default is
.IR kB "."

.TP
.BI --bigxy " <n>"
Like
.B --xy
but operates on the image slides, not the thumbnails.  Scales image
slides to some medium width and height (e.g.
.IR 400 "),"
adjusting their other dimension accordingly.  Useful if your digital 
camera spits out large images, like 1600x1200.  The originals aren't 
affected, but scaled copies of your images are generated
and thumbnails link to these copies.  Clicking on the scaled
copies in the HTML slides lets users see the full unscaled images.
You must use
.B -f
between two consecutive runs when you've changed the value of
.BR "--bigxy" .

.TP
.BI --bigy " <n>"
Like
.B -y
but operates on the image slides, not the thumbnails.  Scales image
slides to some medium height (e.g.
.IR 400 "),"
adjusting their width accordingly.  Useful if your digital camera
spits out large images, like 1600x1200.  The originals aren't affected,
but scaled copies of your images are generated
and thumbnails link to these copies.  Clicking on the scaled
copies in the HTML slides lets users see the full unscaled images.
You must use
.B -f
between two consecutive runs when you've changed the value of
.BR "--bigy" .

.TP
.BI --cf
Generates
.I captions
from file names (strips suffix).

.TP
.BI --cc [=<s>]
Generates
.I captions
from image comment tag.
If no argument is given,
.B llgal
first tries the standard comment (for instance JFIF or GIF), and then
tries Exif comments if the previous one is empty.

An argument such as
.I std
or
.I exif
might be added to force the use of only standard comment
or only Exif comment.

An argument such as
.I exif,std
will make
.B llgal
try Exif comment first.

An argument such as
.I std+exif
will use the combination of standard and Exif comments.

Passing
.I --cc
without argument is thus equivalent to passing
.I --cc std,exif\fR.

.TP
.BI --ct
Add image timestamp tag to the generated captions.

.TP
.BI --ctf " strftime_format"
Change timestamp in captions using a strftime format.

.TP
.BI --con " options"
Command line options to pass on to
.BR convert
internally (see its man page).  This affects all thumbnails
and, if
.BI --bigxy or --bigy
is given, the medium-size slides too.  You can set the
.I -quality
or go crazy with
.IR -negate ", " -noise ", etc."
(the last two only work with
.BR convert " if " ImageMagick " is installed)."
.BI --con
may be used several times on the same command line.

.TP
.BI --exclude " <s>"
Exclude files whose name matches \fBs\fR.

.TP
.BI -i " <file>"
Name of the main thumbnail index file.  The default is
.IR index ,
as desirable for most web servers.
The default extension is
.IR html
and might be changed with
.I --php
or the
.I www_extension
configuration option.

.TP
.BI --include " <s>"
Include files whose name matches \fBs\fR and where previously excluded.

.TP
.BI -k
Use the image captions for the HTML slide titles.
The default behavior is to use the image names.

.TP
.BI -L
Do not create slides and thumbnails for links (including video, file and url),
but list them after the main gallery index.
Might be used when the directory only contains subgalleries and thus does
not need any slide or thumbnail.

.TP
.BI --li
Replace link labels in slides (usually \fBIndex\fR, \fBPrev\fR and \fBNext\fR)
with images (usually \fBindex.png\fR, \fBprev.png\fR and \fBnext.png\fR).

.TP
.BI --lt
Replace link labels in slides (usually \fBPrev\fR and \fBNext\fR) with
a thumbnail to preview previous/next slide.
If passed together with
.BI --li \fR,
thumbnail preview is used for links to previous/next slide
while the image is for the link to the index is kept. 

.TP
.BI -n
Use the image file names for the HTML slide files.  Otherwise
the default behavior is to simply name your slides
.IR 1.html ", " 2.html ", "
and so on.

.TP
.BI --nc
Omit the image count from the captions.

.TP
.BI --next-gal " <url>"
Add links to the previous gallery located by
.IR <url> \fR.
This option is used internally for recursive galleries, and
thus not documented in
.BI --help \fR.

.TP
.BI -p " <n>"
The cellpadding value of the thumbnail index tables.
The default is 3.

.TP
.BI --php
Change the default extension of generated webpages from
.IR html
to
.IR php \fR.
Note that template names are not modified and keep their
.IR html
extension even if they contain some PHP code.
Note that
.B llgal
will only remove existing webpages corresponding to this
extension when generating a new gallery or cleaning.

.TP
.BI --parent-gal
Add links to the parent directory.
This option is used internally for recursive galleries, and
thus not documented in
.BI --help \fR.
These links are stored as a header and a footer for the index.
The text in the links might be changed through the
.B parent_gallery_link_text
configuration option.

.TP
.BI --prev-gal " <url>"
Add links to the previous gallery located by
.IR <url> \fR.
This option is used internally for recursive galleries, and
thus not documented in
.BI --help \fR.

.TP
.BI -r
Omit the film effect altogether.  For a simpler look you
can also set the thumbnail background to be the same as the main
index page background with the tile background-color option in the
.IR llgal.css " file."

.TP
.BI --Rl
Add links between subgalleries.

.TP
.BI -S
Each subdirectory will get a dedicated slide.
If a captions file exists, only the subdirectories that
it defines will be processed.
If no captions file exists,
.B llgal
will process all subdirectories but those whose name begins
with a dot.

Contrary to
.B -R
this option will not make
.B llgal
run recursively in subdirectories.
.B -S
does only define the list of subdirectories that appear
in the current gallery.

.TP
.B -s
For the simplest setup, omit all HTML slides.  Clicking the thumbnails on 
the main page will just take users to the plain image files.

.TP
.BI --sort " [rev]<name|iname|size|time|none>"
Change sort criteria when scanning files in the working directory.
Default is \fBname\fR.
Setting to the empty string means \fBnone\fR.
\fBiname\fR is case insensitive sort by names.
\fBdate\fR means \fBtime\fR.
\fBrev\fR might be added for reverse sort.

.TP
.BI -t " <n>"
Height (in pixels) of the tiled image used to simulate the top
and bottom film effect on the thumbnail index page.  This
is 21 for the default
.I .tile.png
image used, but you should set it otherwise if you replace that
file with your own design.

.TP
.BI --title " <s>"
Substitutes the string 
.I <s>
for "<!--TITLE-->" in the index. The default is "Index of Pictures".

.TP
.BI -u
Write image captions under each thumbnail on the index page.
If you have a
.I captions
file, then the captions are read from there.

.TP
.BI -w " <n>"
Set the thumbnail rows to be
.I <n>
images wide in the main index file.  Default is 5.

.TP
.BI --www
Make all
.B llgal
files world-readable.

.TP
.BI --wx " <n>"
Set the thumbnail rows to be 
.I <n>
pixels wide at maximum. The number of thumbnails per row, given in
.BI -w
is reduced if necessary. Default is to honor
.BI -w
without regard to the resulting row width.

.TP
.BI --xy " <n>"
Scale thumbnails to
.I <n>
pixels along their longest dimension.  This value is passed to
.B pnmscale
and only works properly for
.I jpg
images.

.TP
.BI -y " <n>"
Scale all thumbnails to the same height of 
.IR <n> " pixels."
The default is 75 pixels.


.SH CAPTIONS
When called with
.I --gc
.B llgal
generates (or updates if already existing) the
.IR captions
file in the
.IR .llgal
subdirectory.

When
.I --gc
is not passed, if the
.IR captions
file exists,
.B llgal
will automatically use it to generate slide captions in the gallery.
If
.IR captions
does not exist,
.B llgal
generates captions on the fly and use them in the gallery.

Generating the
.IR captions
file with
.I --gc
before actually using it makes it possible to modify them
(especially to add comments)
or change the order of the slides in the gallery

.B IMG: <filename> ---- <caption>
.RS
defines an image (when omitted,
.B IMG:
is the default type).
.RE
.B MVI: <filename> ---- <linktext> ---- <caption>
.RS
defines a movie.
.RE
.B TXT: <text in slide> ---- <caption>
.RS
defines a text slide.
.RE
.B LNK: <url> ---- <linktext> ---- <caption>
.RS
defines a link slide.
.RE
.B FIL: <url> ---- <linktext> ---- <caption>
.RS
defines a link to another file (typically neither an image nor a movie)
.RE
.B DIR: <dir> ---- <linktext> ---- <caption>
.RS
defines a subdirectory slide.
.RE
.B TITLE: <title>
.RS
defines the title of the gallery.
.RE
.B INDEXHEAD: <one header>
.RS
defines a header (multiple ones are possible).
.RE
.B INDEXFOOT: <one footer>
.RS
defines a footer (multiple ones are possible).
.RE
.B PARENT: <linktext>
.RS
defines the label of the link to the parent gallery.
.RE
.B PREV: <linktext> ---- <url>
.RS
defines the label of the link to the previous gallery located by <url>.
.RE
.B NEXT: <linktext> ---- <url>
.RS
defines the label of the link to the next gallery located by <url>.
.RE

.TP
Note that you can use whatever HTML syntax in the captions.
.RE
Line begining with a
.RI #
are ignored.

When generating a captions file, the
.BI captions.header
file is inserted at the top of the file to detail
the syntax.


.SH CONFIGURATION

Before parsing command line options, llgal reads several configuration
files. It starts with
.IR /etc/llgal/llgalrc
then reads
.IR $HOME/.llgal/llgalrc
then the 
.IR .llgal/llgalrc
file in the gallery directory
and finally the local
.IR .llgal/llgalrc
file.
Additional configuration files may also be defined with the
.I --config
option.

These files may change llgal configuration in the same way command
line options do, and even more.
All following options may also be used on the command line through
.I "--option 'variable = value'"\fR.

See also
.IR /etc/llgal/llgalrc
for details about these options and their default values.

.B llgal directories:

.I llgal_share_dir = \fI"path"
.RS
The location of llgal share directory where template are stored.
Usually \fB/usr/share/llgal\fR or \fB/usr/local/share/llgal\fR.
.RE
.I user_share_dir = \fI"path"
.RS
The location of the per-user share directory where template are stored.
If they exists, these files are used instead of the system-wide files.
Default is \fB$HOME/.llgal\fR.
.RE
.I template_dir = \fI"path"
.RS
Additional template directories [--templates].
This option may be used multiple times.
.RE

.B Names of generic llgal files:

.I captions_header_filename = \fI"filename"
.RS
Name of the captions header file that is inserted at the begining of
generated captions files.
Default is \fBcaptions.header\fR.
.RE
.I css_filename = \fI"filename"
.RS
Name of the CSS file.
Default is \fBllgal.css\fR.
.RE
.I filmtile_filename = \fI"filename"
.RS
Name of the film tile image.
Default is \fBtile.png\fR.
.RE
.I index_link_image_filename = \fI"filename"
.RS
Change image name for link to the index.
Default is \fB"index.png"\fR.
.RE
.I next_slide_link_image_filename = \fI"filename"
.RS
Change image name for link to the next slide.
Default is \fB"next.png"\fR.
.RE
.I previous_slide_link_image_filename = \fI"filename"
.RS
Change image name for link to the previous slide.
Default is \fB"prev.png"\fR.
.RE
.I indextemplate_filename = \fI"filename"
.RS
Name of the HTML index template.
Default is \fBindextemplate.html\fR.
.RE
.I slidetemplate_filename = \fI"filename"
.RS
Name of the HTML slide template.
Default is \fBslidetemplate.html\fR.
.RE

.B Location and name of generated files:

.I local_llgal_dir = \fI"subdirectory name"
.RS
The name of the subdirectory where llgal generated files will be stored.
Default is \fB.llgal\fR.
.RE
.I index_filename = \fI"filename"
.RS
Name of the generated index file [-i <s>].
Default is \fBindex\fR.
.RE
.I slide_filenameprefix = \fI"filename prefix"
.RS
Prefix of generated HTML slide filenames.
Default is \fB""\fR.
.RE
.I slide_filenameprefix_nofile = \fI"filename prefix"
.RS
Prefix of slide filenames when generated from filename
while there's no file associated (text, link, ...).
Default is \fBNOFILE\fR.
.RE
.I scaled_image_filenameprefix = \fI"filename prefix"
.RS
Prefix used to determine slide-image filenames from original images
(in case of --bigxy or --bigy).
Default is \fBscaled_\fR.
.RE
.I thumbnail_image_filenameprefix = \fI"filename prefix"
.RS
Prefix used to determine thumbnail filenames from original images.
Default is \fBthumb_\fR.
.RE
.I captions_filename = \fI"filename"
.RS
Name of the caption file that will be generated when llgal is called with --gc,
or will be automatically used if it exists to generate slide captions.
Default is \fBcaptions\fR.
.RE

.B Index:

.I index_cellpadding = <pixels>
.RS
Cellpadding in the index table [-p <n>].
Default is \fB3\fR.
.RE
.I list_links = <0/1>
.RS
List links after the main gallery thumbnail index [-L].
Default is \fB0\fR (disabled).
.RE
.I pixels_per_row = <pixels>
.RS
Pixels per row of thumbnails in index [-wx <n>].
Default is \fB0\fR (unlimited).
.RE
.I thumbnails_per_row = <pixels>
.RS
Thumbnails per row in index [-w <n>].
Default is \fB5\fR.
.RE
.I thumbnail_height_max = <pixels>
.RS
Maximal height of thumbnails [-y <n>].
Default is \fB75\fR.
.RE
.I thumbnail_width_max = <pixels>
.RS
Maximal width of thumbnails [--xy <n>]
Default is \fB0\fR (unlimited).
.RE
.I show_caption_under_thumbnails = <0/1>
.RS
Write captions under thumbnails [-u].
Default is \fB0\fR (disabled).
.RE
.I show_no_film_effect = <0/1>
.RS
Omit film effect [-r].
Default is \fB1\fR (enabled).
.RE
.I tile_height = <pixels>
.RS
Film tile height [-t <n>].
Default is \fB21\fR.
.RE

.B Slides:

.I make_no_slides = <0/1>
.RS
Make no slides [-s].
Default is \fB0\fR (make slides).
.RE
.I make_slide_filename_from_filename = <0/1>
.RS
Use filenames as slide filenames [-n].
Default is \fB0\fR (disabled).
.RE
.I make_slide_filename_from_extension = <0/1>
.RS
Also use extension in slide filename when generated from filename.
Default is \fB0\fR (disabled).
.RE
.I slide_width_max = <pixels>
.RS
Maximal width of slides [--bigy <n>].
Default is \fB0\fR (unlimited).
.RE
.I slide_height_max = <pixels>
.RS
Maximal height of slides [--bigxy <n>, --bigy <n>].
Default is \fB0\fR (unlimited).
.RE
.I text_slide_width = <pixels>
.RS
Default width of text slides.
Default is \fB400\fR.
.RE
.I text_slide_height = <pixels>
.RS
Default height of text slides.
Default is \fB300\fR.
.RE
.I index_link_image = <0/1>
.RS
Use an image instead of a text label for the link to the index [--li].
Default is \fB0\fR (disabled).
.RE
.I prev_slide_link_image = <0/1>
.RS
Use an image instead of a text label for the link to the previous slide [--li].
Default is \fB0\fR (disabled).
.RE
.I next_slide_link_image = <0/1>
.RS
Use an image instead of a text label for the link to the next slide [--li].
Default is \fB0\fR (disabled).
.RE
.I prev_slide_link_preview = <0/1>
.RS
Use a thumbnail preview instead of a text label for the link to the previous slide [--lt].
Default is \fB0\fR (disabled).
.RE
.I next_slide_link_preview = <0/1>
.RS
Use a thumbnail preview instead of a text label for the link to the next slide [--lt].
Default is \fB0\fR (disabled).
.RE
.I make_slide_title_from_caption = <0/1>
.RS
Generate slide titles from captions [-k].
Default is \fB0\fR (disabled).
.RE

.B Captions:

.I captions_removal_line = \fI"string"
.RS
This line will be added to the caption file llgal will generate when called with --gc.
If the user doesn't want igal to remove this caption file when called with --clean,
he just needs to remove this line from the file.
Default is \fB"REMOVE THIS LINE IF LLGAL SHOULD NOT REMOVE THIS FILE"\fR.
.RE
.I make_caption_from_filename = <0/1>
.RS
Generate captions from filenames [-C].
Default is \fB0\fR (disabled).
.RE
.I make_caption_from_image_comment = ",-separated strings of +-separated strings"
.RS
Generate captions from image comment tag [--cc].
Default is \fB""\fR (disabled).
.RE
.I make_caption_from_image_comment = <0/1>
.RS
Add image timestamp to generated captions [--ct].
Default is \fB0\fR (disabled).
.RE
.I show_dimensions = <0/1>
.RS
Show image dimensions [-a, -ad].
Default is \fB0\fR (disabled).
.RE
.I show_size = <0/1>
.RS
Show file sizes [-a, -as].
Default is \fB0\fR (disabled).
.RE
.I show_no_slide_counter = <0/1>
.RS
Do not show slide counter in captions [--nc].
Default is \fB0\fR (show counter).
.RE

.B Text:

.I index_title = \fI"string"
.RS
Title of the gallery [--title <s>].
Default is \fB"Index of pictures"\fR.
.RE
.I parent_gallery_link_text = \fI"string"
.RS
Label of the link to the parent directory.
Default is \fB"Back to parent gallery"\fR.
.RE
.I prev_gallery_link_text = \fI"string"
.RS
Label of the link to the previous gallery.
Default is \fB"Previous gallery "\fR.
.RE
.I next_gallery_link_text = \fI"string"
.RS
Label of the link to the next gallery.
Default is \fB"Next gallery "\fR.
.RE
.I index_link_text = \fI"string"
.RS
Label of the link from a slide to the index.
Default is \fB"Index"\fR.
.RE
.I prev_slide_link_text = \fI"string"
.RS
Label of the link from a slide to the prev one.
Default is \fB"Prev&gt;&gt;"\fR.
.RE
.I next_slide_link_text = \fI"string"
.RS
Label of the link from a slide to the next one.
Default is \fB"Next&gt;&gt;"\fR.
.RE
.I MVI_link_text = \fI"string"
.RS
Text prefixing the filename when generating link text for movies without
a captions file.
Default is \fB"Open movie "\fR.
.RE
.I FIL_link_text = \fI"string"
.RS
Text prefixing the filename when generating link text for files without
a captions file.
Default is \fB"Download file "\fR.
.RE
.I DIR_link_text = \fI"string"
.RS
Text prefixing the filename when generating link text for directories
without a captions file.
Default is \fB"Open subgallery "\fR.
.RE
.I alt_full_text = \fI"string"
.RS
Text shown as an image alternative for full-size images in slides.
Default is \fB""\fR.
.RE
.I alt_scaled_text = \fI"string"
.RS
Text shown as an image alternative for scaled images in slides.
Default is \fB"Scaled image "\fR.
.RE
.I alt_thumbnail_text = \fI"string"
.RS
Text shown as an image alternative for thumbnails in the index.
Default is \fB"Thumbnail "\fR.
.RE
.I over_scaled_text = \fI"string"
.RS
Text shown when the mouse pointer is over a scaled image in a slide.
Default is \fB"Click to see full size"\fR.
.RE
.I over_thumbnail_text = \fI"string"
.RS
Text shown when the mouse pointer is over a thumbnail.
Default is \fB"Click to enlarge "\fR.
.RE
.I over_index_link_text = \fI"string"
.RS
Text shown when the mouse pointer is over a link from a slide to the index.
Default is \fB"Return to the index"\fR.
.RE
.I over_prev_slide_link_text = \fI"string"
.RS
Text shown when the mouse pointer is over a link from a slide to the previous one.
Default is \fB"Previous slide "\fR.
.RE
.I over_next_slide_link_text = \fI"string"
.RS
Text shown when the mouse pointer is over a link from a slide to the next one.
Default is \fB"Next slide "\fR.
.RE
.I show_size_unit = \fI"string"
.RS
Unit to be used when printing sizes [-asu <s>]
Default is \fB"kB"\fR.
.RE
.I timestamp_format_in_caption = "timestamp format"
.RS
Generate captions from image comment tag [--ctf <s>].
Default is \fB"%Y-%m-%d %H:%M:%S"\fR.
.RE

.B Recursion:

.I make_recursive = <0/1>
.RS
Run recursively in subdirectories [-R].
Default is \fB0\fR (disabled).
.RE
.I link_subgalleries = <0/1>
.RS
Add links between subgalleries [--Rl].
Default is \fB0\fR (disabled).
.RE
.I parent_gallery_link = <0/1>
.RS
Add links to the parent directory [--parent].
Default is \fB0\fR (disabled).
.RE
.I prev_gallery_link = \fI"string"
.RS
Add links to the previous subgallery [--prev-gal <url>].
Default is \fB""\fR (disabled).
.RE
.I next_gallery_link = \fI"string"
.RS
Add links to the next subgallery [--next-gal <url>].
Default is \fB""\fR (disabled).
.RE

.B What files to insert in the gallery:

.I image_extensions = \fI"|-separated strings"
.RS
Extensions that are matched when searching images
Default is \fB"jpe?g|tiff?|png|gif"\fR.
.RE
.I movie_extensions = \fI"|-separated strings"
.RS
Extensions that are matched when searching movies
Default is \fB"mpe?g|mov|avi"\fR.
.RE
.I add_all_files = <0/1>
.RS
Add all files to the list of entries, not only images and movies [-A].
Default is \fB0\fR (disabled).
.RE
.I add_subdirs = <0/1>
.RS
Add subdirectories to the list of entries [-S].
Default is \fB0\fR (disabled).
.RE
.I exclude = \fI"string"
.RS
Exclude files whose name matches [--exclude <s>].
This option may be used several times.
Dot begining files and html files are excluded by default.
.RE
.I include = \fI"string"
.RS
Include files whose name matches and were previously excluded [--include <s>].
This option may be used several times.
The order of includes and excludes is respected.
.RE
.I sort_criteria = \fI"string"
.RS
Sort criteria when scanning files in the working directory.
Default is \fBname\fR.
.RE

.B Various:

.I convert_options = \fI"string"
.RS
Options to pass to convert [--con <s>].
This option may be used several times.
Default is \fB""\fR.
.RE
.I scaled_convert_options = \fI"string"
.RS
Additional options to pass to convert when creating slides.
Default is \fB""\fR.
.RE
.I thumbnail_convert_options = \fI"string"
.RS
Additional options to pass to convert when creating thumbnails.
Default is \fB""\fR.
.RE
.I www_access_rights = <0/1>
.RS
Make all generated files world readable [--www].
Default is \fB0\fR (disabled).
.RE
.I www_extension = \fI"string"
.RS
Extension of generated webpages [--php].
Default is \fB"html"\fR.
.RE
.I config_file = <s>
.RS
Additional configuration file [--config <s>].
This option may be used several times.
.RE


.SH LANGUAGE
All configuration options produce english text by default.
If you wish to create your gallery in another language, you should
create an additional configuration file (or modify the system-wide
one) to update all configuration options of the
.B Text
section.

Additionally, you might have to modify several static strings in
the templates (\fBindextemplate.html\fR and \fBslidetemplate.html\fR),
for instance \fBIndex\fR, \fBPrev\fR and \fBNext\fR.


.SH CHARACTER ENCODING
If a filename contains non-ascii characters which are not safely
representable in a URL,
.BI llgal
will escape them using the method RFC 2396 specifies.
This may raise problems if the web server has a different notion
of character encoding than the machine
.BI llgal
runs on.
See also
.I http://www.w3.org/TR/html4/appendix/notes.html#h-B.2\n"


.SH NOTES
Note that all numerical options may be resetted to their default value
by setting them a negative value.


.SH FILES
.RE
.I /etc/llgal/llgalrc
.I $HOME/.llgal/llgalrc
.I .llgal/llgalrc
.RS
System-wide, per-user and local configuration files. See
.SM
.B CONFIGURATION
for details.
.RE
.I /usr/share/llgal/captions.header
.RS
Captions syntax description file that is inserted at the top
of generated captions file.

.RE
.I /usr/share/llgal/llgal.css
.RS
The default style sheet template.
.RE
.I /usr/share/llgal/tile.png
.RS
The tiled image used for the film effect.
.RE
.I /usr/share/llgal/index.png
.RS
The link image used for the index.
.RE
.I /usr/share/llgal/prev.png
.RS
The link image used for the previous slide.
.RE
.I /usr/share/llgal/next.png
.RS
The link image used for the next slide.
.RE
All files are required on the website.
.BR llgal
will copy them to the local
IR .llgal
file during gallery generation.

.RE
.I /usr/share/llgal/indextemplate.html
.RS
The default index template file.
.RE
.I /usr/share/llgal/slidetemplate.html
.RS
The default file used to generate slides.
.RE
These files are not required on the website.
But,
.BR llgal
will thus them to generate HTML webpages og the gallery.

The user may change all these templates by storing files with
the same name in its user template directory
.IR $HOME/.llgal
or in the local
.IR .llgal
directory.
The former defines user-specific templates that will be used
each time the user generate a gallery.
The later defines gallery-specific templates that will be used
for the local gallery.
A local template is used by default if it exists.
A user template is used if it exists and no local template exists.
Finally, system-wide templates are used if no local and user
templates override them.

It is also possible to add custom template directories (with
.I --templates
) that will be used to get templates before trying in the user
and in the system-wide template directories.

The option
.IR --gt
might be used to get copies of template files in the local
or in the user template directory.


.SH EXAMPLES
Run
.B llgal
in a directory with 
.IR jpg ", " gif ", " png ", " mpg " or " avi
files to see what it does.  Then
play with the options described above and use
.B -h
if you need a quick listing.


.SH BUGS
There are always some.  If you find any let me know.


.SH AUTHOR
Brice Goglin <Brice.Goglin@ens-lyon.org>
