.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH llgalrc 5 "NOVEMBER 2006"



.SH NAME
llgalrc \- Configuration file for llgal




.SH Names of generic llgal files:

.I captions_header_filename = \fI"filename"
.RS
Name of the captions header file that is inserted at the beginning of
generated captions files.
Default is
.BR captions.header .
.RE
.I css_filename = \fI"filename"
.RS
Name of the CSS file.
Default is \fBllgal.css\fR.
.RE
.I filmtile_filename = \fI"filename"
.RS
Name of the film tile image.
Default is \fBtile.png\fR.
Note that it must match the one that is used in the CSS file.
.RE
.I index_link_image_filename = \fI"filename"
.RS
Change image name for link to the index.
Default is \fBindex.png\fR.
.RE
.I next_slide_link_image_filename = \fI"filename"
.RS
Change image name for link to the next slide.
Default is \fBnext.png\fR.
.RE
.I previous_slide_link_image_filename = \fI"filename"
.RS
Change image name for link to the previous slide.
Default is \fBprev.png\fR.
.RE
.I indextemplate_filename = \fI"filename"
.RS
Name of the HTML index template.
Default is \fBindextemplate.html\fR.
.RE
.I slidetemplate_filename = \fI"filename"
.RS
Name of the HTML slide template.
Default is \fBslidetemplate.html\fR.
.RE




.SH Location of llgal files if available on the web

.I css_location = \fI"url"
.RS
The location of the CSS on the web instead of a local one
.RB [ "--uc <url>" ].
If ending with a slash,
.I css_filename
will be appended.
.RE
.I filmtile_location = \fI"url"
.RS
The location of the filmtile image on the web instead of a local one
.RB [ "--ui <url>" ].
If ending with a slash,
.I filmtile_filename
will be appended.
.RE
.I index_link_image_location = \fI"url"
.RS
The location of the index link image on the web instead of a local one
.RB [ "--ui <url>" ].
If ending with a slash,
.I index_link_image_filename
will be appended.
.RE
.I prev_slide_link_image_location = \fI"url"
.RS
The location of the prev slide link image on the web instead of a local one
.RB [ "--ui <url>" ].
If ending with a slash,
.I prev_slide_link_image_filename
will be appended.
.RE
.I next_slide_link_image_location = \fI"url"
.RS
The location of the next slide link image on the web instead of a local one
.RB [ "--ui <url>" ].
If ending with a slash,
.I next_slide_link_image_filename
will be appended.
.RE




.SH Location and name of generated files:

.I local_llgal_dir = \fI"subdirectory name"
.RS
The name of the subdirectory where llgal generated files will be
stored.
This option is only available in system- and user-wide configuration
files.
Default is
.BR .llgal/ .
.RE
.I index_filename = \fI"filename"
.RS
Name of the generated index file
.RB [ "-i <s>" ].
Default is
.BR index .
.RE
.I slide_filenameprefix = \fI"filename prefix"
.RS
Prefix of generated HTML slide filenames.
Default is \fB"slide_"\fR.
Note that this prefix is used to decide what HTML to delete when
.B --clean
is passed.
Setting this option to an empty string will make llgal remove
.I all
HTML files.
.RE
.I scaled_image_filenameprefix = \fI"filename prefix"
.RS
Prefix used to determine slide-image filenames from original images
(in case of
.BR --sx " or " --sy ).
Default is \fB"scaled_"\fR.
.RE
.I thumbnail_image_filenameprefix = \fI"filename prefix"
.RS
Prefix used to determine thumbnail filenames from original images.
Default is \fB"thumb_"\fR.
.RE
.I captions_filename = \fI"filename"
.RS
Name of the caption file that will be generated when llgal is called
with
.BR --gc ,
or will be automatically used if it exists to generate slide captions.
Default is \fB"captions"\fR.
.RE
.I user_scaled_image_filenameprefix = \fI"filename prefix"
.RS
Additional prefix of user-provided scaled images.
Default is \fBmy\fR.
.RE
.I user_thumbnail_image_filenameprefix = \fI"filename prefix"
.RS
Additional prefix of user-provided thumbnails.
Default is \fBmy\fR.
.RE
.I path_separator_replacement = \fI"char"
.RS
Character to use to replace / in the thumbnail/scaled of subdir
images.
Default is \fB@\fR.
.RE




.SH Index:

.I index_cellpadding = <pixels>
.RS
Cellpadding in the index table
.RB [ "-p <n>" ].
Default is
.BR 3 .
.RE
.I list_links = <0/1>
.RS
Display links and text as regular text instead of thumbnails in the main
gallery thumbnail index
.RB [ -L ].
Default is
.BR 0 " (" disabled ).
.RE
.I pixels_per_row = <pixels>
.RS
Pixels per row of thumbnails in index
.RB [ "-wx <n>" ].
Default is
.BR 0 " (" unlimited ).
.RE
.I thumbnails_per_row = <pixels>
.RS
Thumbnails per row in index
.RB [ "-w <n>" ].
Default is
.BR 5 .
.RE
.I thumbnails_dimensions_from_css = <0/1>
.RS
Do not output any absolute thumbnails size in HTML code and assume the
CSS style sheet will take care of it (in table.index [td.thumb [img]]).
Default is
.BR 0 " (" disabled ).
.RE
.I thumbnail_height_max = <pixels>
.RS
Maximal height of thumbnails
.RB [ "--ty <n>" ].
Default is
.BR 75 .
Changing this value does not affect the maximal width (see
.IR thumbnail_width_max ).
.RE
.I thumbnail_width_max = <pixels>
.RS
Maximal width of thumbnails
.RB [ "--tx <n> "].
If
.B 0
is used, the width is unlimited.
If not
.BR 0 ,
all thumbnails are padded to the given width.
Default is
.BR 113 .
Changing this value does not affect the maximal height (see
.IR thumbnail_height_max ).
.RE
.I show_caption_under_thumbnails = <0/1>
.RS
Write captions under thumbnails
.RB [ -u ].
Default is
.BR 0 " (" disabled ).
.RE
.I show_film_effect = <0/1>
.RS
Show film effect
.RB [ --fe ].
Default is
.BR 0 " (" disabled ).
.RE
.I MVI_link_to_target = <0/1>
.RS
Make movie thumbnails links point to the movie instead of
the corresponding slide.
Default is
.BR 1 " (" "link to the movie" ")."
.RE
.I FIL_link_to_target = <0/1>
.RS
Make file thumbnails links point to the file instead of
the corresponding slide.
Default is
.BR 1 " (" "link to the file" ")."
.RE
.I DIR_link_to_target = <0/1>
.RS
Make directory thumbnails links point to the movie instead of
the corresponding slide.
Default is
.BR 1 " (" "link to the directory" ")."
.RE
.I LNK_link_to_target = <0/1>
.RS
Make link thumbnails point to the link instead of
the corresponding slide.
It is similar to using
.I LNKNOSLIDE:
entries instead of
.IR LNK: .
Default is
.BR 1 " (" "link to the link target" ")."
.RE



.SH Slides:

.I make_no_slides = <0/1>
.RS
Make no slides
.RB [ -s ].
Default is
.BR 0 " (" "make slides" ).
.RE
.I make_slide_filename_from_filename = <0/1>
.RS
Use filenames as slide filenames
.RB [ -n ].
Default is
.BR 0 " (" disabled ).
.RE
.I make_slide_filename_from_extension = <0/1>
.RS
Also use extension in slide filename when generated from filename.
Default is
.BR 0 " (" disabled ).
.RE
.I slide_dimensions_from_css = <0/1>
.RS
Do not output any absolute image size in the HTML code and assume the
CSS style sheet will take care of it (in table.slide td.image-slide img).
Default is
.BR 0 " (" disabled ).
.RE
.I slide_width_max = <pixels>
.RS
Maximal width of slides
.RB [ "--sx <n>" ].
Default is
.BR 0 " (" unlimited ).
.RE
.I slide_height_max = <pixels>
.RS
Maximal height of slides
.RB [ "--sy <n>" ].
Default is
.BR 0 " (" unlimited ).
.RE
.I text_slide_width = <pixels>
.RS
Default width of text slides.
Default is
.BR 400 .
.RE
.I text_slide_height = <pixels>
.RS
Default height of text slides.
Default is
.BR 300 .
.RE
.I index_link_image = <0/1>
.RS
Use an image instead of a text label for the link to the index
.RB [ --li ].
Default is
.BR 0 " (" disabled ).
.RE
.I prev_slide_link_image = <0/1>
.RS
Use an image instead of a text label for the link to the previous
slide
.RB [ --li ].
Default is
.BR 0 " (" disabled ).
.RE
.I next_slide_link_image = <0/1>
.RS
Use an image instead of a text label for the link to the next slide
.RB [ --li ].
Default is
.BR 0 " (" disabled ).
.RE
.I prev_slide_link_preview = <0/1>
.RS
Use a thumbnail preview instead of a text label for the link to the
previous slide
.RB [ --lt ].
Default is
.BR 0 " (" disabled ).
.RE
.I next_slide_link_preview = <0/1>
.RS
Use a thumbnail preview instead of a text label for the link to the
next slide
.RB [ --lt ].
Default is
.BR 0 " (" disabled ).
.RE
.I link_between_last_and_first = <0/1>
.RS
Generate links between last and first slides or galleries.
Default is
.BR 1 " (" enabled ).
.RE
.I make_slide_title_from_caption = <0/1>
.RS
Generate slide titles from captions
.RB [ -k ].
Default is
.BR 0 " (" disabled ).
.RE
.I show_exif_tags = <tag1,tag2,...>
.RS
Display a table of EXIF tags under each image slide
.RB [ --exif ].
The tags are given with their name in
.B exiftool -list
and separated with a comma.
.RE
.I show_all_exif_tags = <0/1>
.RS
Display a table of all available EXIF tags under each image slide
.RB [ --exif ].
.RE
.I slide_link_to_full_image = <0/1>
.RS
Link scaled image in slides to full unscaled images
.RB [ --nf ].
Default is
.BR 1 " (" enabled ).
.RE


.SH Captions:

.I captions_removal_line = \fI"string"
.RS
This line will be added to the caption file llgal will generate when
called with
.BR --gc .
If the user doesn't want llgal to remove this caption file when called
with
.BR --clean ,
he just needs to remove this line from the file.
Default is \fB"REMOVE THIS LINE IF LLGAL SHOULD NOT REMOVE THIS FILE"\fR.
.RE
.I make_caption_from_filename = <0/1>
.RS
Generate captions from filenames.
The extension is removed, except for directories.
.RB [ --cf ].
Default is
.BR 0 " (" disabled ).
.RE
.I make_caption_from_extension = <0/1>
.RS
Generate captions from filenames with their extension.
.BR 0 " (" disabled ).
.RE
.I make_caption_from_image_comment = ",-separated strings of +-separated strings"
.RS
Generate captions from image comment tag
.RB [ --cc ].
Default is \fB""\fR
.RB ( disabled ).
.RE
.I make_caption_from_image_timestamp = <0/1>
.RS
Add image timestamp to generated captions
.RB [ --ct ].
Default is
.BR 0 " (" disabled ).
.RE
.I show_dimensions = <0/1>
.RS
Show image dimensions
.RB [ -a ", " -ad ].
Default is
.BR 0 " (" disabled ).
.RE
.I show_size = <0/1>
.RS
Show file sizes
.RB [ -a ", " -as ].
Default is
.BR 0 " (" disabled ).
.RE
.I slide_counter_format = \fI"format"
.RS
Change the format of the counter on the slides.
\fB%n\fR is replaced with the slide number, \fB%0n\fR gets leading zeros,
and \fB%t\fR is replaced with the number of slides.
Default is \fB"&nbsp;&nbsp;&nbsp;(%0n/%t)"\fR.
Slide counter may be disabled by setting to an empty string
.RB [ --nc ].
.RE




.SH Text:

.I index_title_default = \fI"string"
.RS
Default title of the gallery.
May be overridden with [\-\-title <s>] or TITLE: in the captions file.
Default is \fB"Index of pictures"\fR.
.RE
.I parent_gallery_link_text = \fI"string"
.RS
Label of the link to the parent directory.
Default is \fB"Back to parent gallery"\fR.
.RE
.I prev_gallery_link_text = \fI"string"
.RS
Label of the link to the previous gallery.
Default is \fB"Previous gallery "\fR.
.RE
.I next_gallery_link_text = \fI"string"
.RS
Label of the link to the next gallery.
Default is \fB"Next gallery "\fR.
.RE
.I index_link_text = \fI"string"
.RS
Label of the link from a slide to the index.
Default is \fB"Index"\fR.
.RE
.I prev_slide_link_text = \fI"string"
.RS
Label of the link from a slide to the prev one.
Default is \fB"Prev&gt;&gt;"\fR.
.RE
.I next_slide_link_text = \fI"string"
.RS
Label of the link from a slide to the next one.
Default is \fB"Next&gt;&gt;"\fR.
.RE
.I MVI_link_text = \fI"string"
.RS
Text prefixing the filename when generating link text for movies without
a captions file.
Default is \fB"Open movie "\fR.
.RE
.I FIL_link_text = \fI"string"
.RS
Text prefixing the filename when generating link text for files without
a captions file.
Default is \fB"Download file "\fR.
.RE
.I DIR_link_text = \fI"string"
.RS
Text prefixing the filename when generating link text for directories
without a captions file.
Default is \fB"Open subgallery "\fR.
.RE
.I alt_full_text = \fI"string"
.RS
Text shown as an image alternative for full-size images in slides.
Default is \fB""\fR.
.RE
.I alt_scaled_text = \fI"string"
.RS
Text shown as an image alternative for scaled images in slides.
Default is \fB"Scaled image "\fR.
.RE
.I alt_thumbnail_text = \fI"string"
.RS
Text shown as an image alternative for thumbnails in the index.
Default is \fB"Thumbnail "\fR.
.RE
.I alt_film_tile_text = \fI"string"
.RS
Text shown as an image alternative for the film tile in the index.
Default is \fB"Film Tile"\fR.
.RE
.I over_scaled_text = \fI"string"
.RS
Text shown when the mouse pointer is over a scaled image in a slide.
Default is \fB"Click to see full size "\fR.
.RE
.I over_thumbnail_text = \fI"string"
.RS
Text shown when the mouse pointer is over a thumbnail.
Default is \fB"Click to enlarge "\fR.
.RE
.I over_index_link_text = \fI"string"
.RS
Text shown when the mouse pointer is over a link from a slide to the index.
Default is \fB"Return to the index"\fR.
.RE
.I over_prev_slide_link_text = \fI"string"
.RS
Text shown when the mouse pointer is over a link from a slide to the previous one.
Default is \fB"Previous slide "\fR.
.RE
.I over_next_slide_link_text = \fI"string"
.RS
Text shown when the mouse pointer is over a link from a slide to the next one.
Default is \fB"Next slide "\fR.
.RE
.I show_size_unit = \fI"string"
.RS
Unit to be used when printing sizes
.RB [ "--asu <s>" ]
Default is \fB"kB"\fR.
.RE
.I timestamp_format_in_caption = "timestamp format"
.RS
Change the strftime format used when generating captions from image date
.RB [ "--ct <s>" ].
Default is \fB"%Y-%m-%d %H:%M:%S"\fR.
.RE
.I credits_text = \fI"string"
.RS
Credits text at the bottom of the index
Default is \fB"created with <a href="http://home.gna.org/llgal">llgal</a>"\fR.
.RE




.SH What files to insert in the gallery:

.I image_extensions = \fI"|-separated strings"
.RS
Extensions that are matched when searching images
Default is \fB"jpg|jpeg|png|gif|tif|tiff|bmp"\fR.
.RE
.I movie_extensions = \fI"|-separated strings"
.RS
Extensions that are matched when searching movies
Default is \fB"mpg|mpeg|avi|mov|ogm|wmv"\fR.
.RE
.I add_all_files = <0/1>
.RS
Add all files to the list of entries, not only images and movies
.RB [ -A ].
Default is
.BR 0 " (" disabled ).
.RE
.I add_subdirs = <0/1>
.RS
Add subdirectories to the list of entries
.RB [ -S ].
Default is
.BR 0 " (" disabled ).
.RE
.I exclude = \fI"string"
.RS
Exclude files whose name matches
.RB [ "--exclude <s>" ].
This option may be used several times.
Dot beginning files and html files are excluded by default.
.RE
.I include = \fI"string"
.RS
Include files whose name matches and were previously excluded
.RB [ "--include <s>" ].
This option may be used several times.
The order of includes and excludes is respected.
.RE
.I sort_criteria = \fI"string"
.RS
Sort criteria when scanning files in the working directory.
Default is \fB"name"\fR.
.RE




.SH Sections:

.I section_dir = \fI"subdir"
.RS
Include subdirectory contents in the gallery
.RB [ "-P <subdir>" ].
This option may be used several times.
Subdirectory path must be given relatively to the working directory.
Default is to use the content of the working directory.
.RE
.I recursive_sections = <0/1>
.RS
Add all subdirectories to the list of sections
.RB [--Pall].
Default is
.BR 0 " (" disabled ).
.RE
.I entitle_sections = <0/1>
.RS
Add the subdirectory name as a title at the beginning each section
.RB [ --Ps ].
Default is
.BR 0 " (" disabled ).
.RE
.I separate_sections = <0/1>
.RS
Add a horizontal line at the beginning of each section in the index
.RB [ --Ps ].
Default is
.BR 0 " (" disabled ).
.RE




.SH Recursion:

.I recursive = <0/1>
.RS
Run recursively in subdirectories
.RB [ -R ].
Default is
.BR 0 " (" disabled ).
.RE
.I link_subgalleries = <0/1>
.RS
Add links between subgalleries
.RB [ --Rl ].
Default is
.BR 0 " (" disabled ).
.RE
.I parent_gallery_link = <0/1>
.RS
Add links to the parent directory
.RB [ --parent ].
Default is
.BR 0 " (" disabled ).
.RE




.SH Various:

.I additional_configuration_file = \fI"filename"
.RS
Additional configuration file that is parsed immediately
(before processing the following lines)
.RB [ "--config <s>" ].
This option may be used several times.
.RE
.I additional_template_dir = \fI"path"
.RS
Additional template directories
.RB [ --templates ].
This option may be used multiple times.
.RE
.I codeset = \fI"codeset"
.RS
Codeset to be set in HTML headers
.RB [ "--codeset <s>" ].
.RE
.I language = \fI"locale"
.RS
Language to be used for generated text in HTML pages
.RB [ "--lang <s>" ].
If set, the
.B LANGUAGE
environment variable might prevent this option from working.
.RE
.I scaled_create_command = \fI"string"
.RS
Command to use to create scaled images for slides.
Default is \fB"convert \-\-scale <MAXW>x<MAXH> \-\- <IN> <OUT>"\fR.
See
.B THUMBNAILS AND SCALED IMAGES GENERATION
for details.
.RE
.I thumbnail_create_command = \fI"string"
.RS
Command to use to create thumbnails for the index.
Default is \fB"convert \-\-scale <MAXW>x<MAXH> \-\- <IN> <OUT>"\fR.
See
.B THUMBNAILS AND SCALED IMAGES GENERATION
for details.
.RE
.I force_image_regeneration = <0/1>
.RS
Force regeneration of thumbnails and scaled images
.RB [ -f ].
Default is
.BR 0 " (" disabled ).
.RE
.I verbose = <0/1>
.RS
Print notice messages
.RB [ -v ].
Default is
.BR 0 " (" disabled ).
.RE
.I www_access_rights = <0/1>
.RS
Make all generated files world readable
.RB [ --www ].
Default is
.BR 0 " (" disabled ).
.RE
.I www_extension = \fI"string"
.RS
Extension of generated webpages
.RB [ --php ].
Default is \fB"html"\fR.
.RE




.SH SEE ALSO
.PP
.BR llgal (1)

The
.I llgalrc
template file provided within the documentation directory.



.SH AUTHOR
Brice Goglin
