#!/bin/sh
set -e
#DEBHELPER#

# Prepare to move a conffile without triggering a dpkg question
prep_mv_conffile() {
    CONFFILE="$1"

    if [ -e "$CONFFILE" ]; then
	md5sum="`md5sum \"$CONFFILE\" | sed -e \"s/ .*//\"`"
	old_md5sum="`sed -n -e \"/^Conffiles:/,/^[^ ]/{\\\\' $CONFFILE'{s/.* //;p}}\" /var/lib/dpkg/status`"
	if [ "$md5sum" = "$old_md5sum" ]; then
	    rm -f "$CONFFILE"
	fi
    fi
}

case "$1" in
install|upgrade)
    if dpkg --compare-versions "$2" le "0.11-1"; then
	prep_mv_conffile "/etc/llgalrc"
    fi
esac
